name: Send SMS Every Hour

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  send_sms:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twilio

    - name: Send SMS
      env:
        account_sid: ${{ secrets.ACe030b767e282529de332d9e61ba5be94 }}
        auth_token: ${{ secrets.478923d44ce35e1a282a260b5d3e2ad4 }}
      run: |
        python send_sms.py
        
